#!/bin/bash
# Quick Setup & Deploy Script for Forum API CD
# Copy-paste commands dibawah satu per satu ke terminal

echo "=== FORUM API - Quick CD Setup ==="
echo ""
echo "⚠️  SEBELUM menjalankan script ini, pastikan:"
echo "✓ Railway account sudah aktif (https://railway.app)"
echo "✓ Project & PostgreSQL service sudah di-create di Railway"
echo "✓ Sudah catat: RAILWAY_TOKEN dan DB credentials (PGHOST, PGPORT, PGUSER, PGPASSWORD, PGDATABASE)"
echo ""
echo "Jika sudah, lanjut ke STEP-STEP di bawah."
echo ""
echo "========================================="
echo ""

echo "STEP 1: Verifikasi gh (GitHub CLI) installed"
echo "----------------------------------------"
echo "Jalankan:"
echo "  gh --version"
echo ""

echo "STEP 2: Add RAILWAY_TOKEN ke GitHub Secrets"
echo "----------------------------------------"
echo "Ganti <YOUR_RAILWAY_TOKEN> dengan token dari Railway:"
echo "  gh secret set RAILWAY_TOKEN --body '<YOUR_RAILWAY_TOKEN>'"
echo ""

echo "STEP 3: Add Database Credentials ke GitHub Secrets"
echo "----------------------------------------"
echo "Ganti nilai sesuai credentials dari Railway PostgreSQL service:"
echo "  gh secret set PGHOST --body 'your-host-from-railway'"
echo "  gh secret set PGPORT --body '5432'"
echo "  gh secret set PGUSER --body 'postgres'"
echo "  gh secret set PGPASSWORD --body 'your-password-from-railway'"
echo "  gh secret set PGDATABASE --body 'railway'"
echo ""

echo "STEP 4: Verifikasi Secrets Tersimpan"
echo "----------------------------------------"
echo "Jalankan:"
echo "  gh secret list"
echo "Harus tampil:"
echo "  RAILWAY_TOKEN"
echo "  PGHOST"
echo "  PGPORT"
echo "  PGUSER"
echo "  PGPASSWORD"
echo "  PGDATABASE"
echo ""

echo "STEP 5: Update & Push Latest Code"
echo "----------------------------------------"
echo "Jalankan:"
echo "  git add ."
echo "  git commit -m 'final: complete CD setup with Railway secrets'"
echo "  git push origin feature/complete-forum-api"
echo ""

echo "STEP 6: Merge ke Main untuk Trigger CD"
echo "----------------------------------------"
echo "Opsi A - Merge via CLI:"
echo "  git checkout main"
echo "  git pull origin main"
echo "  git merge feature/complete-forum-api"
echo "  git push origin main"
echo ""
echo "Opsi B - Merge via GitHub Web UI:"
echo "  1. Buka: https://github.com/ROBBYARSANI/forum-api/pulls"
echo "  2. Cari PR dari feature/complete-forum-api → main"
echo "  3. Klik 'Merge pull request' → 'Confirm merge'"
echo ""

echo "STEP 7: Monitor Deployment di Actions"
echo "----------------------------------------"
echo "1. Buka: https://github.com/ROBBYARSANI/forum-api/actions"
echo "2. Tunggu workflow 'Continuous Deployment' selesai"
echo "3. Cek job 'deploy' status (harus PASS ✓)"
echo ""

echo "STEP 8: Verifikasi Live Deployment"
echo "----------------------------------------"
echo "1. Buka Railway: https://railway.app"
echo "2. Lihat service Node.js → Domains → copy public URL"
echo "3. Test endpoint:"
echo "   curl https://your-api.up.railway.app/health"
echo ""

echo "========================================="
echo "Kalau ada error, check SETUP_CD_DEPLOYMENT.md untuk troubleshooting"
echo "========================================="
