#!/bin/bash

# Railway Deployment Setup Guide
# This script helps you set up the RAILWAY_TOKEN secret for GitHub Actions

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "              🚀 RAILWAY DEPLOYMENT SETUP GUIDE"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

# Step 1: Explain what's needed
echo "📋 STEP 1: Get your Railway Token"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go to: https://railway.app/account/tokens"
echo ""
echo "Actions:"
echo "  1. Click 'Create Token' button"
echo "  2. Copy the generated token"
echo "  3. Keep it safe - you'll need it in Step 2"
echo ""
echo "⚠️  NOTE: This token grants access to your Railway account!"
echo "         Never share it publicly or commit to git."
echo ""

# Step 2: Add secret to GitHub
echo "📋 STEP 2: Add RAILWAY_TOKEN to GitHub Secrets"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go to: https://github.com/ROBBYARSANI/forum-api/settings/secrets/actions"
echo ""
echo "Actions:"
echo "  1. Click 'New repository secret' button"
echo "  2. In 'Name' field, enter: RAILWAY_TOKEN"
echo "  3. In 'Secret' field, paste your Railway token"
echo "  4. Click 'Add secret'"
echo ""

# Step 3: Verify setup
echo "📋 STEP 3: Verify Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To verify the secret is set up correctly:"
echo ""
echo "  1. Go to: https://github.com/ROBBYARSANI/forum-api/settings/secrets/actions"
echo "  2. You should see 'RAILWAY_TOKEN' in the list"
echo "  3. Make a push to master branch (or manually trigger workflow)"
echo "  4. Go to: https://github.com/ROBBYARSANI/forum-api/actions"
echo "  5. Check 'Continuous Deployment' workflow run"
echo "  6. The deployment should execute 'railway deploy --force'"
echo ""

# Step 4: Check CD Workflow
echo "📋 STEP 4: How CD Workflow Uses RAILWAY_TOKEN"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "The CD workflow (.github/workflows/cd.yml) does:"
echo ""
echo "  Step 1: Install Railway CLI"
echo "    $ npm install -g @railway/cli@latest"
echo ""
echo "  Step 2: Export RAILWAY_TOKEN"
echo "    $ export RAILWAY_TOKEN=<your_secret_token>"
echo ""
echo "  Step 3: Deploy to Railway"
echo "    $ railway deploy --force"
echo ""
echo "  Step 4: Verify with Health Check"
echo "    - Calls GET /health endpoint"
echo "    - Retries up to 60 times with 5-second intervals"
echo "    - Waits up to 5 minutes for deployment to be ready"
echo ""
echo "  Step 5: Run Smoke Tests"
echo "    - Tests GET /health endpoint"
echo "    - Tests GET /status endpoint"
echo "    - Confirms API is responding correctly"
echo ""

# Step 5: Troubleshooting
echo "❓ TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If deployment fails:"
echo ""
echo "1. Check GitHub Actions logs"
echo "   Go to: https://github.com/ROBBYARSANI/forum-api/actions"
echo "   Click on failed workflow run to see detailed logs"
echo ""
echo "2. Verify RAILWAY_TOKEN is set"
echo "   Go to: https://github.com/ROBBYARSANI/forum-api/settings/secrets/actions"
echo "   Confirm RAILWAY_TOKEN exists"
echo ""
echo "3. Check Railway dashboard"
echo "   Go to: https://railway.app/dashboard"
echo "   Look for deployment logs and errors"
echo ""
echo "4. Verify project exists on Railway"
echo "   Check: https://railway.app/dashboard"
echo "   Your project should be visible"
echo ""
echo "5. Test Railway CLI locally"
echo "   $ npm install -g @railway/cli"
echo "   $ export RAILWAY_TOKEN=your_token"
echo "   $ railway project"
echo "   $ railway link  (if needed)"
echo "   $ railway deploy --force"
echo ""

# Step 6: Additional Info
echo "ℹ️  ADDITIONAL INFORMATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Railway Project:"
echo "  Dashboard: https://railway.app/dashboard"
echo "  Docs: https://docs.railway.app"
echo ""
echo "GitHub Actions:"
echo "  Workflows: https://github.com/ROBBYARSANI/forum-api/actions"
echo "  Settings: https://github.com/ROBBYARSANI/forum-api/settings/secrets/actions"
echo ""
echo "Forum API:"
echo "  Production: https://forum-api-production-5ea8.up.railway.app"
echo "  Health: https://forum-api-production-5ea8.up.railway.app/health"
echo "  Status: https://forum-api-production-5ea8.up.railway.app/status"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "✅ Setup complete! Push to master branch to trigger CD workflow."
echo "═══════════════════════════════════════════════════════════════════════════════"
